---
# tasks file for apps
- name: Install development environments
  block:
    - name: Install pycharm
      snap:
        name: pycharm-professional
        state: present
        classic: yes
      tags: pycharm

    - name: Install sublime text 3
      block:
        - name: Add GPG key
          apt_key:
            url: https://download.sublimetext.com/sublimehq-pub.gpg
            state: present
        - name: Make sure https sources work
          apt:
            name: apt-transport-https
            state: present
        - name: Add sublime to sources
          template:
            src: sublime-text.list
            dest: /etc/apt/sources.list.d/sublime-text.list
            owner: root
            group: root
            mode: u=rw,g=rw,o=r
        - name: Install sublime
          apt:
            name: sublime-text
            update_cache: yes
            state: latest
      tags: sublime
            
    - name: Install vscode
      snap:
        name: code
        state: present
        classic: yes
      tags: vscode

- name: Install communications software
  block:
    - name: Install Slack
      snap:
        name: slack
        state: present
        classic: yes
      tags: slack

          
