---
# tasks file for apps

- name: Install Programming thingz
  block:
    - name: Install DockerCE
      block:
        - name: Uninstall old Docker
          apt:
            name:
              - docker
              - docker-engine
              - docker.io
              - containerd
              - runc
            state: absent
        - name: Add docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
            state: present
        - name: Add docker repository
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release }} stable"
            state: present
            filename: docker
        - name: Install docker prerequisites
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common
            state: latest
            update_cache: yes
        - name: Install docker CE
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: latest
            update_cache: yes
        - name: Create docker group
          group:
            name: docker
            state: present
        - name: Add user to docker group
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes
      tags: docker,never

    - name: Install golang
      vars:
        go_version: 1.17.8
      block:
        - name: Download go tarball
          get_url:
            url: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
            dest: ~/Downloads/go{{ go_version }}.linux-amd64.tar.gz
            checksum: sha256:980e65a863377e69fd9b67df9d8395fd8e93858e7a24c9f55803421e453f4f99
          become: no
        - name: Extract go to /opt
          unarchive:
            src: ~{{ ansible_user_id }}/Downloads/go{{ go_version }}.linux-amd64.tar.gz
            dest: /opt/
            creates: /opt/go
        - name: Add go binaries to PATH
          lineinfile:
            path: "{{ item }}"
            state: present
            line: "export PATH=$PATH:/opt/go/bin"
            regexp: '^export PATH=$PATH:/opt/go/bin$'
          loop:
            - /etc/zsh/zprofile
            - /etc/profile
        - name: Set up GOPATH
          file:
            path: ~/go
            state: directory
            mode: u=rwx,g=rx,o=
          become: no
        - name: add GOPATH to profile
          lineinfile:
            path: ~/.zshenv
            state: present
            line: "export GOPATH=~{{ ansible_user_id }}/go"
          become: no
        - name: add GOPATH/bin to profile
          lineinfile:
            path: ~/.zshenv
            state: present
            line: "export PATH=${PATH}:${GOPATH}/bin"
          become: no
      tags: golang
    
    - name: Install lua
      vars:
        lua_version: "5.4"
      block:
        - name: Install lua packages
          apt:
            name:
              - liblua{{ lua_version }}-0
              - liblua{{ lua_version }}-dev
              - libtcl
              - luarocks
              - lua{{ lua_version }}
              - tcl
              - tcl-dev
            state: present
            update_cache: yes
        - name: Install lua filesystem and luaposix
          command: "luarocks install {{ item }}"
          loop:
            - luaposix
            - luafilesystem
      tags: lua

    - name: Install lmod
      vars:
        lmod_version: 8.6.14
      block:
        - name: Download lmod
          get_url:
            url: https://github.com/TACC/Lmod/archive/refs/tags/{{ lmod_version }}.tar.gz
            dest: ~{{ ansible_user_id }}/Downloads/Lmod-{{ lmod_version }}.tar.gz
            checksum: sha256:29a15b2bad9bdd7cfef5ebc4aa41561c59e3d4c8271fa937a0ec1c5b79373b1f
        - name: Uncompress lmod
          unarchive:
            src: ~{{ ansible_user_id }}/Downloads/Lmod-{{ lmod_version }}.tar.gz
            dest: /tmp
            creates: /tmp/Lmod-{{ lmod_version }}
        - name: Add build directory
          file:
            path: /tmp/Lmod-{{ lmod_version }}/build
            state: directory
        - name: Configure lmod compile
          command: "../configure --prefix=/opt/lmod"
          args:
            chdir: /tmp/Lmod-{{ lmod_version }}/build
            creates: /tmp/Lmod-{{ lmod_version }}/build/Makefile
        - name: Install lmod
          make:
            chdir: /tmp/Lmod-{{ lmod_version }}/build
            target: install
          become: yes
        - name: Add lmod to profile
          file:
            src: /opt/lmod/lmod/{{ lmod_version }}/init/profile
            dest: /etc/profile.d/z00_lmod.sh
            state: link
          become: yes
        - name: Add custom /software to profile
          copy:
            src: z99_lmod.sh
            dest: /etc/profile.d/z99_lmod.sh
            mode: u=rw,g=r,o=r
          become: yes
      become: no
      tags: lmod

- name: Install graphics programs
  block:
    - name: Install inkscape
      apt:
        name:
          - inkscape
          - gimp
        state: latest
