---
# tasks file for roles/base

- name: Install commonly used packages
  apt:
    name:
      - 'build-essential'
      - 'curl'
      - 'git'
      - 'libldap2-dev'
      - 'libmariadb-dev'
      - 'libpq-dev'
      - 'libsasl2-dev'
      - 'make'
      - 'mariadb-client'
      - 'mariadb-server'
      - 'net-tools'
      - 'pkg-config'
      - 'postgresql'
      - 'postgresql-client'
      - 'postgresql-common'
      - 'traceroute'
      - 'wget'
      - 'xz-utils'
    update_cache: yes
    autoremove: yes
