---
# tasks file for roles/base

- name: Upgrade and install all the things
  import_tasks: update.yaml
  become: yes
  tags: update,upgrade

- name: Install common packages
  import_tasks: install.yaml
  become: yes
  tags: install_common
